# Generated by Django 2.2.4 on 2020-06-15 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('product_company', models.CharField(blank=True, max_length=256, null=True)),
                ('product_model', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('hsn_code', models.IntegerField(choices=[(8471, 8471), (8443, 8443), (8523, 8523), (8504, 8504), (8507, 8507)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('hsn_code', models.IntegerField(choices=[(8471, 8471), (8443, 8443), (8523, 8523), (8504, 8504), (8507, 8507)], default=8471)),
                ('gst', models.IntegerField(choices=[(5, 5), (12, 12), (18, 18), (28, 28)], default=18)),
                ('ordered', models.BooleanField(default=False)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('buyer_gst', models.CharField(max_length=256)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_gst', models.CharField(blank=True, max_length=256, null=True)),
                ('buyer_address', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField(default=0)),
                ('gst', models.IntegerField(choices=[(5, 5), (12, 12), (18, 18), (28, 28)], default=5)),
                ('quantity', models.IntegerField(default=0)),
                ('gst_amount', models.IntegerField(blank=True, null=True)),
                ('c_gst', models.IntegerField(blank=True, null=True)),
                ('s_gst', models.IntegerField(blank=True, null=True)),
                ('i_gst', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('hsn_code', models.IntegerField(choices=[(8471, 8471), (8443, 8443), (8523, 8523), (8504, 8504), (8507, 8507)], default='8443')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.Client')),
                ('items', models.ManyToManyField(default=1, to='src.OrderItem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_product', to='src.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
