# Generated by Django 2.2.4 on 2020-06-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
