# Generated by Django 2.2.4 on 2020-06-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200616_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
