# Generated by Django 2.2.4 on 2020-06-16 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200616_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orders',
            field=models.IntegerField(auto_created=True, default=uuid.uuid4),
        ),
    ]
