# Generated by Django 2.2.4 on 2020-06-16 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200616_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.IntegerField(auto_created=True, default=uuid.uuid4),
        ),
    ]
