# Generated by Django 2.2.4 on 2020-06-16 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20200616_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.BigIntegerField(auto_created=True, default=uuid.uuid4),
        ),
    ]
