# Generated by Django 2.2.4 on 2020-06-16 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20200616_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=10),
        ),
    ]
