# Generated by Django 2.2.4 on 2020-06-16 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20200616_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
