# Generated by Django 2.2.4 on 2020-06-16 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200616_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
