# Generated by Django 2.2.4 on 2020-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_bill_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
