# Generated by Django 2.2.4 on 2020-06-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20200617_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
