# Generated by Django 2.2.4 on 2020-06-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='c_gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='i_gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='s_gst',
        ),
    ]
