# Generated by Django 2.2.4 on 2020-06-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20200618_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
