# Generated by Django 2.2.4 on 2020-06-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
