# Generated by Django 2.2.4 on 2020-06-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20200618_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderedadfa',
            new_name='ordered',
        ),
    ]
