# Generated by Django 2.2.4 on 2020-06-18 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20200618_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
