# Generated by Django 2.2.4 on 2020-06-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_bill_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
    ]
